apiVersion: v1
kind: Namespace
metadata:
  name: k8s-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-startup-time
  namespace: k8s-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-startup-time
  template:
    metadata:
      labels:
        app: k8s-startup-time
    spec:
      serviceAccountName: k8s-startup-time
      containers:
      - name: k8s-startup-time
        image: ghcr.io/mojojoji/k8s-startup-time-startup-time:127b403cc59caad36e76c96d6f7aa2120288fcf6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: HEALTH_SERVER_IMAGE
          value: "ghcr.io/mojojoji/k8s-startup-time-health-server:127b403cc59caad36e76c96d6f7aa2120288fcf6"
        resources:
          requests:
            cpu: "50m"    # Minimum CPU needed to start
            memory: "32Mi" # Minimum memory needed to start
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-startup-time
  namespace: k8s-test
spec:
  selector:
    app: k8s-startup-time
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-startup-time
  namespace: k8s-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-startup-time
  namespace: k8s-test
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-startup-time
  namespace: k8s-test
subjects:
- kind: ServiceAccount
  name: k8s-startup-time
  namespace: k8s-test
roleRef:
  kind: Role
  name: k8s-startup-time
  apiGroup: rbac.authorization.k8s.io 